vich_uploader:
    db_driver: orm

    mappings:
        blog_images:
            uri_prefix:         '%app.path.blog_images%'
            upload_destination: '%kernel.project_dir%/public%app.path.blog_images%'
            namer: Vich\UploaderBundle\Naming\SmartUniqueNamer


            inject_on_load: true;